workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - android_signing
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build AAB
        script: |
          echo $CM_KEYSTORE | base64 --decode > /tmp/smartcv.jks
          flutter build appbundle --release \
            --android-skip-build-dependency-validation
      - name: Sign AAB
        script: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore /tmp/smartcv.jks \
            -storepass $CM_KEYSTORE_PASSWORD \
            -keypass $CM_KEY_PASSWORD \
            build/app/outputs/bundle/release/app-release.aab \
            $CM_KEY_ALIAS
    artifacts:
      - build/**/outputs/**/*.aab